### ISSUE TITLE
limel-menu: Add support for sub-menus

### ISSUE THREAD

**Issue by adrianschmidt** [Lundalogik/lime-elements#2603]
## New feature motivation

Packers need to have a menu with sub-menus. And it will probably be a generally useful thing.

## New feature description

The thing is already built and being reviewed (and refactored a bit). This issue is here to be an umbrella for the multiple PRs.

https://github.com/Lundalogik/lime-elements/assets/154725/38501c2b-6023-4b74-88f7-8b62c1c94069

## New feature implementation

```[tasklist]
### Tasks
- [ ] https://github.com/Lundalogik/lime-elements/pull/2576
- [ ] https://github.com/Lundalogik/lime-elements/pull/2577
- [ ] https://github.com/Lundalogik/lime-elements/pull/2578
```
